version: '3'

services:
  # app:
  #   build: .
  #   container_name: app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - dbmongo
  dbmongo:
    image: mongo:3.6.4
    container_name: dbmongo
    ports:
      - "27017:27017"
    volumes:
      - .:/data/db
    command: mongod --smallfiles --logpath=/dev/null